
Load data 

```{r}
data <- read.csv("data/train.csv")

head(data)
```

```{r}
names(data)
```



```{r}
model = lm(Burn.Rate ~ Mental.Fatigue.Score + Resource.Allocation + Designation + WFH.Setup.Available + Company.Type + Gender,data=data)
summary(model)
```


```{r}
model = lm(Burn.Rate ~ Mental.Fatigue.Score + Resource.Allocation + Designation + WFH.Setup.Available + Company.Type + Gender + Date.of.Joining ,data=data)
summary(model)
```


```{r}
#data$Date.of.Joining

startdate <- as.Date(min(data$Date.of.Joining),"%Y-%m-%d")
data$DateFormatted <-  as.Date(data$Date.of.Joining,"%Y-%m-%d")

data$NumDays  <- difftime(data$DateFormatted,startdate ,units="days")
#data$NumDays
```


```{r}
model = lm(Burn.Rate ~ Mental.Fatigue.Score + Resource.Allocation + Designation + WFH.Setup.Available + Company.Type + Gender + NumDays ,data=data)
summary(model)
```

```{r}
model_int = lm(Burn.Rate ~ Mental.Fatigue.Score * Resource.Allocation * Designation * WFH.Setup.Available * Company.Type * Gender * NumDays ,data=data)
anova(model, model_int)
```

